### ISSUE TITLE
How to save and load the model

### ISSUE THREAD

**Issue by SRL94** [raffaellopaletta/ftc#2]
Hi, how could I save and load a model?

**Comment by raffaellopaletta** [comment]
Hi, the library does not have a persistent storage. You can save the training set in any external database (mysql, mongo, elastic, etc...). For convenience you can store in the database directly the fuzzy set of a document obtained by the TextClassifier class using method **fuzzyfi** and then using method **add_document** when you initialize the classifier loading data from storage, without re-train.

**Comment by raffaellopaletta** [comment]
SOLVED
